### PR TITLE
Movement Rework

### PR DESCRIPTION
**Pull request by hodgerti**
1. Set the title to exactly what you are adding.
Movement Rework **1.1**
2. Which team is this for?
Character systems
3. Give a short description of what you are implementing:
Added force based movement. Added sprinting. Fixed jump height.

### CODE REVIEW

**Review by moorbren — COMMENTED** [review]
Looks good to me. The sprinting will probably need some networking hook to make it work right, will check it out during the meeting today.

**Review by JasonStallkamp — DISMISSED** [review]

**Comment by JasonStallkamp** [comment]
I am having some issues with sprinting. I believe that your most recent commit ([ee91903](https://github.com/OSUGameDev/LocalWar/pull/36/commits/ee9190339449483fc8a8aca2bd587d9f84ad0451)) removed the sprinting.

**Comment by hodgerti** [comment]
lol I did didn't I. Thats probably fine because the control of activating
it was janky. That will be something I will fix wednesday

**Review by JasonStallkamp — COMMENTED** [review]
jump has a problem when sprinting. We decided it was a non critical bug, and will merge it

**Review by JasonStallkamp — APPROVED** [review]

**Pull request merged**
