### PR TITLE
Networking Bug Fixes and Main Menu Level Selection

### PR DESCRIPTION
**Pull request by JasonStallkamp**
**1. Set the title to exactly what you are adding.**
Networking bug fixes and main menu level selection

**2. Which team is this for?**
Networking

**3. Give a short description of what you are implementing:**
- Added Basic Main Menu Selection
- Added Custom Editor Window for main menu level selection
- Added Server Post Process Build for windows (Linux is built into Unity)
- Fixed FakeNetworking Level Changing bug
- Fixed Socket Closing Bug

### CODE REVIEW

**Comment by JasonStallkamp** [comment]
[Socket not closing bug](https://trello.com/c/rZl8Eurz/7-socket-not-closing-bug)

**Comment by JasonStallkamp** [comment]
[Load correct online scene in fake network manager](https://trello.com/c/ssfHQTrN/6-load-correct-online-scene-in-fake-network-manager)

**Comment by JasonStallkamp** [comment]
[Create a Windows Dedicated Server](https://trello.com/c/7bEYHYp6/2-create-a-windows-dedicated-server)

**Comment by JasonStallkamp** [comment]
[Main Menu level select](https://trello.com/c/JZJKN2Zo/8-main-menu-level-select)

**Review by Nathan127 — APPROVED** [review]
Changes are approved

**Pull request merged**
