### PR TITLE
Ver 0.0.0.1

### PR DESCRIPTION
**Pull request by Alasses**
Create the basic system for Chracter, based on the UML design.

### CODE REVIEW

**Comment by moorbren** [comment]
Good working start to project

Next step is to implement an Event Manager system to allow Networking to start integrating things

**Comment by moorbren** [comment]
Good working start to project

Next step is to implement an Event Manager system to allow Networking to start integrating things

(accidentally closed this)

**Comment by JasonStallkamp** [comment]
[Simple Networking for 0.0.0.1](https://trello.com/c/cSeSONni/1-simple-networking-for-0001)

**Comment by JasonStallkamp** [comment]
[Simple Networking for 0.0.0.1](https://trello.com/c/cSeSONni/1-simple-networking-for-0001)

**Pull request merged**
